#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=16gb
#PBS -l walltime=TIME
#PBS -A open
#PBS -o logs/depth.eid-EXPERIMENTID.EXPERIMENTNAME.log.out
#PBS -e logs/depth.eid-EXPERIMENTID.EXPERIMENTNAME.log.err
#PBS -t 1-1000

set -exo

EXPERIMENT=EXPERIMENTID

# FIRST CHANGE PATH TO EXECUTE
WRK=/path/to/GenoPipe/paper/SyntheticEpitope
EPITOPEID=$WRK/../../EpitopeID
cd $WRK

module load gcc/8.3.1
module load bedtools/2.27.1
module load anaconda3
source activate my-genopipe-env

INFO=`sed "${EXPERIMENT}q;d" depth_simulations.txt`
REF=`awk '{print $1}' <(echo $INFO)`
PROTEIN=`awk '{print $2}' <(echo $INFO)`
LOCUS=`awk '{print $3}'  <(echo $INFO)`
EPITOPE=`awk '{print $4}'  <(echo $INFO)`
BASE=`awk '{print $5}'  <(echo $INFO)`

GENOME=synthetic_genome/$REF\_$PROTEIN-$LOCUS\_$EPITOPE.fa
DATABASE=$WRK/../db/$REF\_EpiID

[ -d logs ] || mkdir logs

# sacCer3 or hg19 depth arrays
allDepths=("10K" "100K" "1M" "10M")
[[ "$REF" =~ "hg19" ]] && allDepths=("100K" "1M" "10M" "20M" "50M")

# Iterate across all depths
for d in ${!allDepths[@]};
do
	SEED=$(($BASE*$d+$PBS_ARRAYID))
	DEPTH=${allDepths[$d]}
	RESULTS=$WRK/results/$REF/$DEPTH/$EPITOPE/$PROTEIN

	[ -d $RESULTS/ID ] || mkdir $RESULTS/ID
	[ -d $RESULTS/runtime ] || mkdir $RESULTS/runtime

	# Set-up Temp directory
	TEMP=$WRK/temp-$EXPERIMENT-$PBS_ARRAYID-$DEPTH
	[ -d $TEMP ] || mkdir $TEMP

	cd $TEMP
	ln -s $RESULTS/FASTQ/Simulation_$PBS_ARRAYID\_R1.fastq.gz
	ln -s $RESULTS/FASTQ/Simulation_$PBS_ARRAYID\_R2.fastq.gz

	# Execute EpitopeID and record time
	cd $EPITOPEID
	start=`date +%s`
	bash identify-Epitope.sh -i $TEMP -o $RESULTS/ID -d $DATABASE -t 6
	end=`date +%s`
	runtime=$((end-start))
	echo "Experiment $EXPERIMENT.$DEPTH.$PBS_ARRAYID ($RESULTS) finished in ${runtime}" > $RESULTS/runtime/Simulation_$PBS_ARRAYID.runtime

	# Clean-up
	rm -r $TEMP
done
