#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=16gb
#PBS -l walltime=00:05:00
#PBS -A open
#PBS -o logs/depth.Reb1.100K.log.out
#PBS -e logs/depth.Reb1.100K.log.err
#PBS -t 1-5

cd /path/to/GenoPipe/paper/SyntheticEpitope

module load bedtools/2.27.1
module load bwa/0.7.15
module load python/2.7.14-anaconda5.0.1

BASE=1000
DEPTH=100K
LOCUS=sacCer3_Reb1-Cterm

GENOME=synthetic_genome/$LOCUS\_R500.fa
OUTPUT=results/$LOCUS\_$DEPTH
SEED=$(($BASE+$PBS_ARRAYID))

start=`date +%s`
bash ../scripts/simulate.sh -i $PBS_ARRAYID -d $DEPTH -s $SEED -g $GENOME -o $OUTPUT -t 4 
end=`date +%s`
runtime=$((end-start))
echo "Reb1 100K simulate in ${runtime}"
