#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=16gb
#PBS -l walltime=02:00:00
#PBS -A open
#PBS -o logs/mix.human.50M.log.out
#PBS -e logs/mix.human.50M.log.err
#PBS -t 1-1000

# Required Software
#install seqtk
#install gzip

WRK=/path/to/GenoPipe/paper/SyntheticEpitope
cd $WRK

REF=hg19
# DEPTH=20M
DEPTH=50M
EPITOPE=R500
AFACTOR=CTCF
BFACTOR=POLR2H

OUTPUT=results/mix_human/$DEPTH
[ -d results/mix_human ] || mkdir results/mix_human
[ -d $OUTPUT ] || mkdir $OUTPUT

MIX=../scripts/mix_fastq.sh
ABASE=results/$REF/$DEPTH/$EPITOPE/$AFACTOR/FASTQ/Simulation_$PBS_ARRAYID
BBASE=results/$REF/$DEPTH/$EPITOPE/$BFACTOR/FASTQ/Simulation_$PBS_ARRAYID

start=`date +%s`
# Titrate out various ratios
for PER in 90 80 70 60 50 40 30 20 10
do
	ODIR=$OUTPUT/$PER\_$AFACTOR\_$BFACTOR/FASTQ
	OBASE=$ODIR/Simulation_$PBS_ARRAYID
	[ -d $ODIR ] || mkdir -p $ODIR
	bash $MIX -p $PER -a $ABASE -b $BBASE -o $OBASE
done
end=`date +%s`
runtime=$((end-start))
echo "Mix ${A_STRAIN} and ${B_STRAIN} from depth at ${DEPTH} simulated in ${runtime}"
