#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l pmem=16gb
#PBS -l walltime=03:00:00
#PBS -A open
#PBS -o logs/sid.cenpk.chip.log.out
#PBS -e logs/sid.cenpk.chip.log.err

# FIRST CHANGE PATH TO EXECUTE
WRK=/path/to/GenoPipe/paper/CENPK-chipseq
cd $WRK

module load gcc
module load samtools
module load bwa
module load anaconda3
source activate ~/work/myconda/genopipe

[ -d logs ] || mkdir logs
[ -d results/ID ] || mkdir -p results/ID

DB=$WRK/../db/sacCer3_VCF
GENOME=$WRK/../input/sacCer3.fa

STRAINID=$WRK/../../StrainID
cd $STRAINID
bash identify-Strain.sh -i $WRK/results/BAM -g $GENOME -o $WRK/results/ID/ -v $DB
