#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l pmem=24gb
#PBS -l walltime=01:00:00
#PBS -A open
#PBS -o logs/filter.count.log.out
#PBS -e logs/filter.count.log.err
#PBS -t 1-14260

module load gcc/9.3.1
module load samtools
module load anaconda3
source activate genopipe

WRK=/path/to/GenoPipe/paper/ENCODE-CellLines
cd $WRK

[ -d logs ] || mkdir logs
[ -d results/BAM-nospike ] || mkdir -p results/BAM-nospike

METADATA=210512_sample_metadata.txt
INFO=`sed "${PBS_ARRAYID}q;d" $METADATA`
ENCFF=`echo $INFO | awk '{print $1}'`
#echo $INFO

BAM=results/BAM/$ENCFF
NOSPIKE=results/BAM-nospike/$ENCFF

# Strip Spike-in
python scripts/filter_spikein.py -b $BAM.bam -g ../input/hg19.fa -o $NOSPIKE.bam
samtools index $NOSPIKE.bam

# Count Bases
[ -f $BAM.bam.bai ] && python scripts/estimate_bp_sequenced.py -b $BAM.bam > $BAM\_bpcount.txt
[ -f $NOSPIKE.bam.bai ] && python scripts/estimate_bp_sequenced.py -b $NOSPIKE.bam > $NOSPIKE\_bpcount.txt
